<a href="https://colab.research.google.com/github/ivywanjage/cdav/blob/main/apple_products_sold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas

In [6]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
pd.__version__
pd.set_option("display.max_columns",None)

In [7]:
counties=pd.Series([4397073,1208333,2162202,1157073])
print(counties)

0    4397073
1    1208333
2    2162202
3    1157073
dtype: int64

In [16]:
df=pd.read_csv("/apple_products_pricing_2020_2026.csv")
df.head()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35

In [17]:
df.tail()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [18]:
df.head(10)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
5,2020-09-26,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.29,43149.46,-1.7,NaN,In Stock,4.7,45
6,2020-09-27,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.06,42587.59,-0.9,NaN,In Stock,4.8,60
7,2020-09-29,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,312.11,26276.64,27.2,NaN,In Stock,4.4,146
8,2020-10-01,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,323.84,31855.01,24.5,Big Billion Days,In Stock,4.7,95
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133

In [19]:
df.tail(20)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
79980,2026-07-31,Amazon,iPhone,iPhone 14 128GB,New,799,78302,503.88,49842.89,36.9,NaN,In Stock,4.8,6543
79981,2026-07-31,Flipkart,iPhone,iPhone 15 128GB,Renewed/Refurbished,799,78302,451.76,39016.28,43.5,NaN,In Stock,4.5,3803
79982,2026-07-31,Flipkart,iPhone,iPhone 15 128GB,New,799,78302,605.37,58534.13,24.2,NaN,In Stock,4.2,2112
79983,2026-07-31,Amazon,iPhone,iPhone 15 128GB,Renewed/Refurbished,799,78302,449.58,38863.40,43.7,NaN,In Stock,4.2,4641
79984,2026-07-31,Flipkart,iPhone,iPhone 15 Pro Max 256GB,New,1199,117502,1018.87,100946.12,15.0,NaN,Low Stock,4.5,4403
79985,2026-07-31,Flipkart,iPhone,iPhone 16 128GB,New,799,78302,695.21,66804.50,13.0,NaN,In Stock,4.7,2994
79986,2026-07-31,Flipkart,iPhone,iPhone 16 128GB,New,799,78302,693.49,69317.61,13.2,NaN,Low Stock,4.5,1162
79987,2026-07-31,Amazon,iPhone,iPhone 16 128GB,New,799,78302,704.55,69188.38,11.8,NaN,In Stock,4.6,2186
79988,2026-07-31,Amazon,iPhone,iPhone 16 128GB,Renewed/Refurbished,799,78302,525.79,44818.21,34.2,NaN,Low Stock,3.9,2016
79989,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,843.77,83516.88,0.6,NaN,Out of Stock,4.7,1060
79990,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,844.47,84171.70,0.5,NaN,In Stock,4.7,893
79991,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,659.77,56416.63,22.3,NaN,In Stock,4.0,853
79992,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,845.93,82352.51,0.4,NaN,In Stock,4.3,1211
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79994,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,837.57,82448.67,1.3,NaN,In Stock,4.3,1407
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [20]:
df.shape

(80000, 14)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               80000 non-null  object
 1   Platform           80000 non-null  object
 2   Product_Category   80000 non-null  object
 3   Model_Name         80000 non-null  object
 4   Condition          80000 non-null  object
 5   Launch_Price_USD   80000 non-null  int64
 6   Launch_Price_INR   80000 non-null  int64
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct       80000 non-null  float64
 10  Sale_Event         6649 non-null   object
 11  Stock_Status       80000 non-null  object
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64
dtypes: float64(4), int64(3), object(7)
memory usage: 8.5+ MB

In [22]:
df.describe()

,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Rating,Reviews_Count
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,963.959125,94467.994250,782.769855,74628.342439,21.418826,4.450099,2405.995925
std,470.086413,46068.468464,461.673970,45117.872172,16.697310,0.269782,1973.630852
min,329.000000,32242.000000,109.930000,9157.680000,-2.000000,3.800000,10.000000
25%,599.000000,58702.000000,432.930000,41686.835000,6.700000,4.300000,896.000000
50%,799.000000,78302.000000,699.740000,67324.020000,21.300000,4.400000,1893.500000
75%,1199.000000,117502.000000,989.112500,96568.117500,36.800000,4.700000,3383.000000
max,1999.000000,195902.000000,2038.970000,203668.710000,73.100000,4.900000,11526.000000

In [23]:
df.columns
#column names

Index(['Date', 'Platform', 'Product_Category', 'Model_Name', 'Condition',
       'Launch_Price_USD', 'Launch_Price_INR', 'Current_Price_USD',
       'Current_Price_INR', 'Discount_Pct', 'Sale_Event', 'Stock_Status',
       'Rating', 'Reviews_Count'],
      dtype='object')

In [24]:
df.dtypes
#the type of each column

Date                  object
Platform              object
Product_Category      object
Model_Name            object
Condition             object
Launch_Price_USD       int64
Launch_Price_INR       int64
Current_Price_USD    float64
Current_Price_INR    float64
Discount_Pct         float64
Sale_Event            object
Stock_Status          object
Rating               float64
Reviews_Count          int64
dtype: object

In [25]:
df.index
#the row labels

RangeIndex(start=0, stop=80000, step=1)

In [26]:
df.size
#the total number of cells

1120000

In [29]:
df["Product_Category"].unique()
#what values appear in that specific column

array(['Watch', 'iPad', 'iPhone', 'Mac'], dtype=object)

In [34]:
df[["Model_Name","Product_Category"]]

                        Model_Name Product_Category
0      Apple Watch Series 6 (44mm)            Watch
1      Apple Watch Series 6 (44mm)            Watch
2      Apple Watch Series 6 (44mm)            Watch
3      Apple Watch Series 6 (44mm)            Watch
4      Apple Watch Series 6 (44mm)            Watch
...                            ...              ...
79995              iPhone 17 128GB           iPhone
79996              iPhone 17 128GB           iPhone
79997              iPhone 17 128GB           iPhone
79998              iPhone 17 128GB           iPhone
79999              iPhone 17 128GB           iPhone

[80000 rows x 2 columns]

In [35]:
df.loc[2,"Platform"]
#row named 2,column named platform

'Amazon'

In [37]:
df.iloc[2,2]
#second row,second column

'Watch'